#------------------------------------------------------------------------------------
# Composite template configuration file
#------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------
# Versioning
#------------------------------------------------------------------------------------
# version: version of the composite
# region: region of the composite (our current ones are Amhara, ETZ, CAS)
version: 1.0
region: 'Amhara'
start_year: 2009
end_year: 2015

#------------------------------------------------------------------------------------
# Inputs
#------------------------------------------------------------------------------------
# landcover_dir: land cover directory where outputs reside
# landcover_suffix: suffix of the product raster filenames
# cloudmask_dir: cloud mask directory where outputs reside
# cloudmask_suffix: suffix of the product raster filenames
# landcover_dir: '/explore/nobackup/projects/3sl/development/cnn_landcover/accuracy-increase-ethiopia/6class-global-standardization-256-4band-v12/results/${region}'
landcover_dir: '/explore/nobackup/projects/3sl/development/cnn_landcover/accuracy-increase-ethiopia/6class-global-standardization-256-4band-v12/results/Amhara-MS_trim_epsg32637'
landcover_suffix: '-toa.6class'
# cloudmask_dir: '/explore/nobackup/projects/3sl/products/cloudmask/v2/${region}'
cloudmask_dir: '/explore/nobackup/projects/3sl/products/cloudmask/v2/Amhara-MS_epsg32637'
cloudmask_suffix: '-toa.cloudmask'

#------------------------------------------------------------------------------------
# Outputs
#------------------------------------------------------------------------------------
# output_dir: output directory to store artifacts
# input_data_regex: input data regex or filename to location where toa imagery resides
# grid_filename: filename where annotated grid is located at
# footprints_filename: filename of footprint file to output (or existing footprint)
# metadata_filename: filename of metadata shapefile with information per grid (or existing metadata file)
output_dir: '/explore/nobackup/projects/ilab/scratch/jacaraba/ethiopia/cnn_landcover_composite/${region}-${version}'
input_data_regex: '/explore/nobackup/projects/3sl/data/VHR/${region}/M1BS/*-toa.tif'
grid_filename: '/explore/nobackup/projects/3sl/auxiliary/Shapefiles/${region}_grid.gpkg'
footprints_filename: '${output_dir}/${region}_M1BS_griddedToa.gpkg'
metadata_filename: '${output_dir}/${region}_M1BS_griddedToa_metadata.gpkg'

#------------------------------------------------------------------------------------
# Filtering
#------------------------------------------------------------------------------------
# stats_list: default stats, Varies for task/input .shp
stats_list:
  - 'median'

# filter_months: filtering inputs by month, set to False if we do not want to filter
filter_months: False
filter_name: '11-05'
remove_months:
  - 6
  - 7
  - 8
  - 9
  - 10

soil_moisture_qa: False
fill_value: 255
burn_area_value: 15

# calculate_nobservations: generate num observations rasters
# calculate_mode_composite: generate mode composites
# calculate_binary_stats: produce binary class frequency of occurence (%) outputs (or others)
# binary_stats: stats to include in the class frequency of occurrence outputs
calculate_nobservations: True
calculate_mode_composite: True
calculate_binary_stats: True
binary_stats:
  - 'pct'
  - 'max'
  - 'median'

calculate_confidence: True
confidence_metrics:
  - 'trend_confidence'
  - 'distribution_confidence'

#------------------------------------------------------------------------------------
# general
#------------------------------------------------------------------------------------
# EPSG for the composite and shapefiles
epsg: 'EPSG:32637'

#------------------------------------------------------------------------------------
# build_footprints
#------------------------------------------------------------------------------------

# input column to add to the file
input_column_field: toa_path

#------------------------------------------------------------------------------------
# extract_metadata
#------------------------------------------------------------------------------------
metadata_fields:
  - all_touched
  # - soil_moisture

join_cols:
  - 'strip_id'

date_column_field: date
date_column_field_format: '%Y%m%d'

#------------------------------------------------------------------------------------
# composite
#------------------------------------------------------------------------------------
use_dask: True
n_partitions: 1000
scheduler: 'processes'

# overwrite mode/nobs/class output tifs (not zarrs)
overwrite_tifs: True
overwrite_zarrs: True

test_name: 'qaTest1'
model_name: 'otcb.v11'
grid_cell_name_pre_str: '${region}.M1BS'
datetime_column: 'datetime'

composite_fields:
  - landcover
  - cloudmask
  - soil_moisture

composite_classes:
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5

#------------------------------------------------------------------------------------
# postprocessing
#------------------------------------------------------------------------------------
# composite post-processing - for now, establish rules for combining class-pct outputs
# for now we can do this here but later might separate so we can combine filtered and unfiltered indiv classes
# not yet implemented 
# the below dictionary corresponds to the thresholds and orders for each class-pct
# eg {0: 1, 1: 33, 2: 25} means output will be combined with other >=1 % on bottom, then tree/shrub >= 33%, then crop >=25%
post_process_combine: True
# Outputs will be stored in epoch/_combined_{combine_name}
combine_name: 'test1'
combine_classes:
  0: 1
  1: 25
  2: 25