#------------------------------------------------------------------------------------
# Composite template configuration file
#------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------
# Versioning
#------------------------------------------------------------------------------------
# version: version of the composite
# region: region of the composite (our current ones are Amhara, ETZ, CAS)
version: 1.0
region: 'Amhara'
start_year: 2009
end_year: 2015

#------------------------------------------------------------------------------------
# Inputs
#------------------------------------------------------------------------------------
# landcover_dir: land cover directory where outputs reside
# landcover_suffix: suffix of the product raster filenames
# cloudmask_dir: cloud mask directory where outputs reside
# cloudmask_suffix: suffix of the product raster filenames
landcover_dir: '/explore/nobackup/projects/3sl/development/cnn_landcover/accuracy-increase-ethiopia/6class-global-standardization-256-4band-v12/results/${region}'
landcover_suffix: '-toa.6class'
cloudmask_dir: '/explore/nobackup/projects/3sl/products/cloudmask/v2/${region}'
cloudmask_suffix: '-toa.cloudmask'

#------------------------------------------------------------------------------------
# Outputs
#------------------------------------------------------------------------------------
# output_dir: output directory to store artifacts
# input_data_regex: input data regex or filename to location where toa imagery resides
# grid_filename: filename where annotated grid is located at
# footprints_filename: filename of footprint file to output (or existing footprint)
# metadata_filename: filename of metadata shapefile with information per grid (or existing metadata file)
output_dir: '/explore/nobackup/projects/ilab/scratch/jacaraba/ethiopia/cnn_landcover_composite/${region}-${version}'
input_data_regex: '/explore/nobackup/projects/3sl/data/VHR/${region}/M1BS/*-toa.tif'
grid_filename: '/explore/nobackup/projects/3sl/auxiliary/Shapefiles/${region}_grid.gpkg'
footprints_filename: '${output_dir}/${region}_M1BS_griddedToa.gpkg'
metadata_filename: '${output_dir}/${region}_M1BS_griddedToa_metadata.gpkg'

#--------------------------------------------
# wooten additions
#--------------------------------------------
# *MW added to filter images - #*TD make more flexible for months and other filters later
# Set to False if we do not want to filter
filter_months: False
# These must be set if above is True
filter_name: '11-05'
remove_months:
  - 6
  - 7
  - 8
  - 9
  - 10

#*MW added to skip this
soil_moisture_qa: False
fill_value: 255
burn_area_value: 15

#*MW overwrite mode/nobs/class output tifs (not zarrs)
overwrite_tifs: True
overwrite_zarrs: True

#*MW options to run
calculate_nobservations: True
# calc_nobs_only: True #*MW temp
calculate_mode_composite: True
# if True, produce binary class frequency of occurence (%) outputs (or others)
calculate_binary_stats: True
binary_stats:
  - 'pct'
  - 'max'
  - 'median'

#--------------------------------------------
# composite post-processing - for now, establish rules for combining class-pct outputs
# for now we can do this here but later might separate so we can combine filtered and unfiltered indiv classes
#--------------------------------------------
#*MW not yet implemented 
# the below dictionary corresponds to the thresholds and orders for each class-pct
# eg {0: 1, 1: 33, 2: 25} means output will be combined with other >=1 % on bottom, then tree/shrub >= 33%, then crop >=25%
post_process_combine: True
# Outputs will be stored in epoch/_combined_{combine_name}
combine_name: 'test1'
combine_classes:
  0: 1
  1: 25
  2: 25

#--------------------------------------------
# general
#--------------------------------------------






# EPSG for the composite and shapefiles
epsg: 'EPSG:32637'



#--------------------------------------------
# build_footprints
#--------------------------------------------






# input column to add to the file
input_column_field: toa_path

#--------------------------------------------
# extract_metadata
#--------------------------------------------
join_cols:
#  - 'tile'
  - 'strip_id'

date_column_field: date
date_column_field_format: '%Y%m%d'

use_dask: True
n_partitions: 1000
scheduler: 'processes'

# default stats, Varies for task/input .shp
stats_list:
  - 'median'

metadata_fields:
  - all_touched
  # - soil_moisture



# projectDir  = '/explore/nobackup/projects/3sl'
# self.auxDir      = os.path.join(self.projectDir, 'auxiliary')
# self.productDir  = os.path.join(self.projectDir, 'products')
# monthly_soil_moisture_filename: '/explore/nobackup/projects/3sl/auxiliary/SoilMoisture_0-10cm/wa_monthly_fldas_soilmoi00_10cm_tavg_<date>.tif'
#--------------------------------------------
# composite
#--------------------------------------------

test_name: 'qaTest1'
model_name: 'otcb.v11'
grid_cell_name_pre_str: '${region}.M1BS'

datetime_column: 'datetime'




composite_fields:
  - landcover
  - cloudmask
  - soil_moisture

composite_classes:
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
