stages: [test]

cpu_validation:
  image: python:3.12
  stage: test
  script:
    - python -m pip install '.[validation,test]'
    - python -m pytest -q
    - ruff check ethiopia_lcluc_tensorflow tests
    - python -m build
    - python -m twine check dist/*
